typography_spectrum: 0.1415875139646232
content_rating:
  adult: false
color:
  brandStrength: 0.9262341957073659
  lightness: 0.8532421642448753
  saturation: 0.1894464639481157
  rhythmicContrast: 0.7994788391515613
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
opengraph:
  type: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/977428a9-bb60-4179-be19-a885e8e69594.png
layout_spectrum: 0.4549843284767121
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e18bf15c-9063-45a2-927b-a26b7cf8608a.jpg
name: thegrid.ai/h-cubo
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e935b9d-cab2-4554-869a-bf9cba8c7f6f.jpg
title: sgedahgsahsfgh
description: tttttttt
